url = "https://qa.my.andela.com/"
usrFld = "okta-signin-username"
email = "test-engineer@andela.com"
pwdFld = "password"
pasword = "Wonder_123"
signBtn = "okta-signin-submit"
newskill = ".skills-top .ng-star-inserted:nth-of-type(2) [type]"
skNameFld = "skillname"
warning = "(Intermediate requires 3.01-5.00 years of experience)"
skName = "Ruby"
sklOpt = "#ruby .mat-option-text"
drpDown = ".mat-select-arrow"
proLvl = "mat-option:nth-of-type(3) > .mat-option-text"
exper = "years"
years = "4"
skill_content = "app-skills-modal > [role] > .ng-star-inserted:nth-of-type(1)"
addSkillBtn = "[type='submit']"
skillBadge = ".skills-badge__content-wrapper"